# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hk3Ju_Ar3c1nCqAV9gnWJWlb40fn-4D
"""

import pandas  as pd
murodil={
    "FISH": ["Xolmatov Murodil", "Mirobidova Rayxona", "Muhsinov Rasuljon", "Soliyev Maqsudjon","Ahmadov Muslimbek", "Jalilov Durbek", "Obidov Ozodbek","Tursunova Muhlisa", "Halilova Muhlisa", "Tojiyeva Ruxshona" ],
    "Yoshi": [ "15", "14", "65", "55", "10", "12", "18", "16", "13", "17", ],
    "Maktab": ["30-maktab", "31-maktab", "32-maktab", "33-maktab", "34-maktab", "35-maktab", "36-maktab", "37-maktab", "38-maktab", "40-maktab"],
    "Jinsi": ["erkak","ayol","erkak","erkak","erkak","erkak","erkak","ayol","ayol","ayol"],
    "Manzil": ["Baxrin MFY", "Baxrin MFY", "Qo'shtepa MFY", "Chaqa MFY", "Oqoltin MFY", "Hurmat MFY","Yangiqishloq MFY","Yakkatut MFY","Hasanqora MFY","Jalayer MFY"],
}
malumotlar = pd.DataFrame(murodil)
print(malumotlar)

FILTR = malumotlar[(malumotlar["Jinsi"]=='erkak') & (malumotlar["Yoshi"]>'15')& (malumotlar["Manzil"]=="Qo'shtepa MFY") ]
print(FILTR)